export const countries = {
  argentina: 'Argentina',
  bolivia: 'Bolivia',
  bulgaria: 'Bulgaria',
  cambodia: 'Cambodia',
  canada: 'Canada',
  colombia: 'Colombia',
  ecuador: 'Ecuador',
  france: 'France',
  greece: 'Greece',
  netherlands: 'Netherlands',
  paraguay: 'Paraguay',
  peru: 'Peru',
  romania: 'Romania',
  thailand: 'Thailand',
  unitedKingdom: 'United Kingdom',
  usa: 'USA',
  vietnam: 'Vietnam',
}

export const places = {
  [countries.argentina]: {
    buenosAires: 'Buenos Aires',
    cafayate: 'Cafayate',
    cordoba: 'Córdoba',
    resistencia: 'Resistencia',
    rosario: 'Rosario',
    salta: 'Salta',
    sanMiguelDeTucuman: 'San Miguel de Tucumán',
    tafiDelValle: 'Tafí del Valle',
    villaCarlosPaz: 'Villa Carlos Paz',
  },
  [countries.bolivia]: {
    cochabamba: 'Cochabamba',
    copacabana: 'Copacabana',
    coroico: 'Coroico',
    islaDelSol: 'Isla del Sol',
    laPaz: 'La Paz',
    samaipata: 'Samaipata',
    santaCruz: 'Santa Cruz',
    sucre: 'Sucre',
    tupiza: 'Tupiza',
  },
  [countries.bulgaria]: {
    sofia: 'Sofia',
  },
  [countries.cambodia]: {
    phnomPenh: 'Phnom Penh',
    siemReap: 'Siem Reap',
  },
  [countries.colombia]: {
    bogota: 'Bogota',
    cali: 'Cali',
    cartagena: 'Cartagena',
    medellin: 'Medellin',
    pasto: 'Pasto',
    popayan: 'Popayan',
    sanAgustin: 'San Agustín',
    taganga: 'Taganga',
    tayronaNationalPark: 'Tayrona National Park',
  },
  [countries.canada]: {
    blackFamilyFarm: 'Black Family Farm, MB',
    bowenIsland: 'Bowen Island, BC',
    brandon: 'Brandon, MB',
    calgary: 'Calgary, AB',
    crossRiverWildernessCentre: 'Cross River Wilderness Centre, BC',
    dawsonCity: 'Dawson City, YT',
    deaseLake: 'Dease Lake, BC',
    dryden: 'Dryden, ON',
    fortNelson: 'Fort Nelson, BC',
    gabriolaIsland: 'Gabriola Island, BC',
    galianoIsland: 'Galiano Island, BC',
    grandPrairie: 'Grand Prairie, AB',
    hope: 'Hope, BC',
    houston: 'Houston, BC',
    invermere: 'Invermere, BC',
    jasper: 'Jasper, AB',
    kelowna: 'Kelowna, BC',
    montreal: 'Montreal, QC',
    ottawa: 'Ottawa, ON',
    quesnel: 'Quesnel, BC',
    regina: 'Regina, SK',
    saultSteMaria: 'Sault Ste. Marie, ON',
    toronto: 'Toronto, ON',
    vancouver: 'Vancouver, BC',
    victoria: 'Victoria, BC',
    whitby: 'Whitby, ON',
    whitehorse: 'Whitehorse, YT',
    winnipeg: 'Winnipeg, MB',
  },
  [countries.ecuador]: {
    banos: 'Baños',
    montanita: 'Montañita',
    quito: 'Quito',
    riobamba: 'Riobamba',
  },
  [countries.france]: {
    paris: 'Paris',
  },
  [countries.greece]: {
    athens: 'Athens',
  },
  [countries.netherlands]: {
    amsterdam: 'Amsterdam',
  },
  [countries.paraguay]: {
    asuncion: 'Asunción',
  },
  [countries.peru]: {
    arequipa: 'Arequipa',
    chiclayo: 'Chiclayo',
    huacachina: 'Huacachina',
    huanchaco: 'Huanchaco',
    huaraz: 'Huaraz',
    lima: 'Lima',
    mancora: 'Máncora',
    puno: 'Puno',
  },
  [countries.romania]: {
    bucharest: 'Bucharest',
  },
  [countries.thailand]: {
    bangkok: 'Bangkok',
    chiangMai: 'Chiang Mai',
    chiangRai: 'Chiang Rai',
    huahin: 'Huahin',
    loei: 'Loei',
    udonThani: 'Udon Thani',
  },
  [countries.unitedKingdom]: {
    london: 'London',
  },
  [countries.usa]: {
    austin: 'Austin, TX',
    charleston: 'Charleston, SC',
    chicago: 'Chicago, IL',
    flagstaff: 'Flagstaff, AZ',
    fortLauderdale: 'Fort Lauderdale, FL',
    houston: 'Houston, TX',
    lasVegas: 'Las Vegas, NV',
    miami: 'Miami, FL',
    nashville: 'Nashville, TN',
    newOrleans: 'New Orleans, LA',
    pasadena: 'Pasadena, CA',
    portland: 'Portland, OR',
    richmond: 'Richmond, KY',
    sacramento: 'Sacramento, CA',
    saltLakeCity: 'Salt Lake City, UT',
    sanFrancisco: 'San Francisco, CA',
  },
  [countries.vietnam]: {
    hoChiMinhCity: 'Ho Chi Minh City',
  },
}
