export const countries = {
  bulgaria: 'Bulgaria',
  cambodia: 'Cambodia',
  canada: 'Canada',
  greece: 'Greece',
  romania: 'Romania',
  thailand: 'Thailand',
  unitedKingdom: 'United Kingdom',
  vietnam: 'Vietnam',
}

export const places = {
  [countries.bulgaria]: {
    sofia: 'Sofia',
  },
  [countries.cambodia]: {
    phnomPenh: 'Phnom Penh',
    siemReap: 'Siem Reap',
  },
  [countries.canada]: {
    blackFamilyFarm: 'Black Family Farm, MB',
    bowenIsland: 'Bowen Island, BC',
    brandon: 'Brandon, MB',
    calgary: 'Calgary, AB',
    crossRiverWildernessCentre: 'Cross River Wilderness Centre, BC',
    dawsonCity: 'Dawson City, YT',
    deaseLake: 'Dease Lake, BC',
    dryden: 'Dryden, ON',
    fortNelson: 'Fort Nelson, BC',
    gabriolaIsland: 'Gabriola Island, BC',
    galianoIsland: 'Galiano Island, BC',
    grandPrairie: 'Grand Prairie, AB',
    hope: 'Hope, BC',
    houston: 'Houston, BC',
    invermere: 'Invermere, BC',
    jasper: 'Jasper, AB',
    kelowna: 'Kelowna, BC',
    montreal: 'Montreal, QC',
    ottawa: 'Ottawa, ON',
    quesnel: 'Quesnel, BC',
    regina: 'Regina, SK',
    saultSteMaria: 'Sault Ste. Marie, ON',
    toronto: 'Toronto, ON',
    vancouver: 'Vancouver, BC',
    victoria: 'Victoria, BC',
    whitby: 'Whitby, ON',
    whitehorse: 'Whitehorse, YT',
    winnipeg: 'Winnipeg, MB',
  },
  [countries.greece]: {
    athens: 'Athens',
  },
  [countries.romania]: {
    bucharest: 'Bucharest',
  },
  [countries.thailand]: {
    bangkok: 'Bangkok',
    chiangMai: 'Chiang Mai',
    chiangRai: 'Chiang Rai',
    huahin: 'Huahin',
    loei: 'Loei',
    udonThani: 'Udon Thani',
  },
  [countries.unitedKingdom]: {
    london: 'London',
  },
  [countries.vietnam]: {
    hoChiMinhCity: 'Ho Chi Minh City',
  },
}
