export const countries = {
  argentina: 'Argentina',
  bolivia: 'Bolivia',
  bulgaria: 'Bulgaria',
  cambodia: 'Cambodia',
  canada: 'Canada',
  china: 'China',
  colombia: 'Colombia',
  ecuador: 'Ecuador',
  france: 'France',
  greece: 'Greece',
  indonesia: 'Indonesia',
  laos: 'Laos',
  mexico: 'Mexico',
  netherlands: 'Netherlands',
  paraguay: 'Paraguay',
  peru: 'Peru',
  romania: 'Romania',
  singapore: 'Singapore',
  thailand: 'Thailand',
  unitedKingdom: 'United Kingdom',
  usa: 'USA',
  vietnam: 'Vietnam',
}

export const places = {
  [countries.argentina]: {
    buenosAires: 'Buenos Aires',
    cafayate: 'Cafayate',
    cordoba: 'Córdoba',
    resistencia: 'Resistencia',
    rosario: 'Rosario',
    salta: 'Salta',
    sanMiguelDeTucuman: 'San Miguel de Tucumán',
    tafiDelValle: 'Tafí del Valle',
    villaCarlosPaz: 'Villa Carlos Paz',
  },
  [countries.bolivia]: {
    cochabamba: 'Cochabamba',
    copacabana: 'Copacabana',
    coroico: 'Coroico',
    islaDelSol: 'Isla del Sol',
    laPaz: 'La Paz',
    samaipata: 'Samaipata',
    santaCruz: 'Santa Cruz',
    sucre: 'Sucre',
    tupiza: 'Tupiza',
  },
  [countries.bulgaria]: {
    sofia: 'Sofia',
  },
  [countries.cambodia]: {
    banLung: 'Ban Lung',
    battambang: 'Battambang',
    kampot: 'Kampot',
    kep: 'Kep',
    phnomPenh: 'Phnom Penh',
    siemReap: 'Siem Reap',
    sihanoukville: 'Sihanoukville',
    sisophon: 'Sisophon',
  },
  [countries.canada]: {
    blackFamilyFarm: 'Black Family Farm, MB',
    bowenIsland: 'Bowen Island, BC',
    brandon: 'Brandon, MB',
    calgary: 'Calgary, AB',
    capeBretonIsland: 'Cape Breton Island',
    crossRiverWildernessCentre: 'Cross River Wilderness Centre, BC',
    dawsonCity: 'Dawson City, YT',
    deaseLake: 'Dease Lake, BC',
    dryden: 'Dryden, ON',
    edmonton: 'Edmonton, AB',
    fortNelson: 'Fort Nelson, BC',
    gabriolaIsland: 'Gabriola Island, BC',
    galianoIsland: 'Galiano Island, BC',
    grandPrairie: 'Grand Prairie, AB',
    halifax: 'Halifax, NS',
    hope: 'Hope, BC',
    houston: 'Houston, BC',
    invermere: 'Invermere, BC',
    jasper: 'Jasper, AB',
    kelowna: 'Kelowna, BC',
    montreal: 'Montreal, QC',
    ottawa: 'Ottawa, ON',
    portHardy: 'Port Hardy, BC',
    princeRupert: 'Prince Rupert, BC',
    quesnel: 'Quesnel, BC',
    regina: 'Regina, SK',
    saultSteMaria: 'Sault Ste. Marie, ON',
    toronto: 'Toronto, ON',
    vancouver: 'Vancouver, BC',
    victoria: 'Victoria, BC',
    whitby: 'Whitby, ON',
    whitehorse: 'Whitehorse, YT',
    winnipeg: 'Winnipeg, MB',
  },
  [countries.china]: {
    beijing: 'Beijing',
    changsha: 'Changsha',
    chengdu: 'Chengdu',
    chongqing: 'Chongqing',
    dali: 'Dali',
    guangzhou: 'Guangzhou',
    hangzhou: 'Hangzhou',
    hongKong: 'Hong Kong',
    jinghong: 'Jinghong',
    kangding: 'Kangding',
    kunming: 'Kunming',
    litang: 'Litang',
    macau: 'Macau',
    nanjing: 'Nanjing',
    nanning: 'Nanning',
    pingyao: 'Pingyao',
    qingdao: 'Qingdao',
    sanya: 'Sanya',
    shanghai: 'Shanghai',
    shangriLa: 'Shangri-la',
    shenzhen: 'Shenzhen',
    wuhan: 'Wuhan',
    xiamen: 'Xiamen',
    xian: 'Xian',
    xiangcheng: 'Xiangcheng',
    yangshuo: 'Yangshuo',
  },
  [countries.colombia]: {
    bogota: 'Bogotá',
    cali: 'Cali',
    cartagena: 'Cartagena',
    medellin: 'Medellín',
    pasto: 'Pasto',
    popayan: 'Popayán',
    sanAgustin: 'San Agustín',
    taganga: 'Taganga',
    tayronaNationalPark: 'Tayrona National Park',
  },
  [countries.ecuador]: {
    banos: 'Baños',
    montanita: 'Montañita',
    quito: 'Quito',
    riobamba: 'Riobamba',
  },
  [countries.france]: {
    paris: 'Paris',
  },
  [countries.greece]: {
    athens: 'Athens',
  },
  [countries.indonesia]: {
    bali: 'Bali',
  },
  [countries.laos]: {
    banKloukhan: 'Ban Kloukhan',
    luangNamtha: 'Luang Namtha',
    luangPrabang: 'Luang Prabang',
    muangNgoi: 'Muang Ngoi',
    nongKhiaw: 'Nong Khiaw',
    savannakhet: 'Savannakhet',
    vangVieng: 'Vang Vieng',
    vientiane: 'Vientiane',
  },
  [countries.mexico]: {
    acapulco: 'Acapulco',
    cancun: 'Cancún',
    chiapasJungle: 'Chiapas Jungle',
    mexicoCity: 'Mexico City',
    playaDelCarmen: 'Playa del Carmen',
    puertoEscondido: 'Puerto Escondido',
    sanCristobalDeLasCasas: 'San Cristóbal de las Casas',
  },
  [countries.netherlands]: {
    amsterdam: 'Amsterdam',
  },
  [countries.paraguay]: {
    asuncion: 'Asunción',
  },
  [countries.peru]: {
    arequipa: 'Arequipa',
    chiclayo: 'Chiclayo',
    huacachina: 'Huacachina',
    huanchaco: 'Huanchaco',
    huaraz: 'Huaraz',
    lima: 'Lima',
    mancora: 'Máncora',
    puno: 'Puno',
  },
  [countries.romania]: {
    bucharest: 'Bucharest',
  },
  [countries.singapore]: {
    singapore: 'Singapore',
  },
  [countries.thailand]: {
    bangkok: 'Bangkok',
    chiangMai: 'Chiang Mai',
    chiangRai: 'Chiang Rai',
    huahin: 'Huahin',
    kanchanaburi: 'Kanchanaburi',
    khonKaen: 'Khon Kaen',
    kohPhiPhi: 'Koh Phi Phi',
    kohSamet: 'Koh Samet',
    krabi: 'Krabi',
    loei: 'Loei',
    lopburi: 'Lopburi',
    maeHongSon: 'Mae Hong Son',
    nakhonRatchasima: 'Nakhon Ratchasima',
    nongKhai: 'Nong Khai',
    pai: 'Pai',
    patong: 'Patong',
    pattaya: 'Pattaya',
    phitsanulok: 'Phitsanulok',
    phuketTown: 'Phuket Town',
    udonThani: 'Udon Thani',
  },
  [countries.unitedKingdom]: {
    london: 'London',
  },
  [countries.usa]: {
    anchorage: 'Anchorage, AK',
    austin: 'Austin, TX',
    boston: 'Boston, MA',
    charleston: 'Charleston, SC',
    chicago: 'Chicago, IL',
    flagstaff: 'Flagstaff, AZ',
    fortLauderdale: 'Fort Lauderdale, FL',
    houston: 'Houston, TX',
    juneau: 'Juneau, AK',
    lasVegas: 'Las Vegas, NV',
    losAngeles: 'Los Angeles, CA',
    miami: 'Miami, FL',
    nantucket: 'Nantucket, MA',
    nashville: 'Nashville, TN',
    newOrleans: 'New Orleans, LA',
    newYork: 'New York, NY',
    northbridge: 'Northbridge, MA',
    parkCity: 'Park City, UT',
    pasadena: 'Pasadena, CA',
    portland: 'Portland, OR',
    richmond: 'Richmond, KY',
    sacramento: 'Sacramento, CA',
    saltLakeCity: 'Salt Lake City, UT',
    sanFrancisco: 'San Francisco, CA',
    seattle: 'Seattle, WA',
  },
  [countries.vietnam]: {
    dongHoi: 'Dong Hoi',
    hanoi: 'Hanoi',
    hoChiMinhCity: 'Ho Chi Minh City',
    hue: 'Hue',
    muiNe: 'Mui Ne',
    nhaTrang: 'Nha Trang',
    ninhBinh: 'Ninh Binh',
    thanhHoa: 'Thanh Hoa',
  },
}
